export const CUSTOMER_LIST_REQUEST = "CUSTOMER_LIST_REQUEST";
export const CUSTOMER_LIST_SUCCESS = "CUSTOMER_LIST_SUCCESS";
export const CUSTOMER_LIST_FAIL = "CUSTOMER_LIST_FAIL";
export const CUSTOMER_LIST_REMOVE_ONE_CUSTOMER =
  "CUSTOMER_LIST_REMOVE_ONE_CUSTOMER";

export const CUSTOMER_GET_REQUEST = "CUSTOMER_GET_REQUEST";
export const CUSTOMER_GET_SUCCESS = "CUSTOMER_GET_SUCCESS";
export const CUSTOMER_GET_FAIL = "CUSTOMER_GET_FAIL";

export const CUSTOMER_UPDATE_REQUEST = "CUSTOMER_UPDATE_REQUEST";
export const CUSTOMER_UPDATE_SUCCESS = "CUSTOMER_UPDATE_SUCCESS";
export const CUSTOMER_UPDATE_FAIL = "CUSTOMER_UPDATE_FAIL";

export const CUSTOMER_DELETE_REQUEST = "CUSTOMER_DELETE_REQUEST";
export const CUSTOMER_DELETE_SUCCESS = "CUSTOMER_DELETE_SUCCESS";
export const CUSTOMER_DELETE_FAIL = "CUSTOMER_DELETE_FAIL";

export const CUSTOMER_ADD_REQUEST = "CUSTOMER_ADD_REQUEST";
export const CUSTOMER_ADD_SUCCESS = "CUSTOMER_ADD_SUCCESS";
export const CUSTOMER_ADD_FAIL = "CUSTOMER_ADD_FAIL";