export const INTERACTION_LIST_REQUEST = "INTERACTION_LIST_REQUEST";
export const INTERACTION_LIST_SUCCESS = "INTERACTION_LIST_SUCCESS";
export const INTERACTION_LIST_FAIL = "INTERACTION_LIST_FAIL";

export const INTERACTION_REQUEST = "INTERACTION_REQUEST";
export const INTERACTION_SUCCESS = "INTERACTION_SUCCESS";
export const INTERACTION_FAIL = "INTERACTION_FAIL";

export const INTERACTION_ADD_REQUEST = "INTERACTION_ADD_REQUEST";
export const INTERACTION_ADD_SUCCESS = "INTERACTION_ADD_SUCCESS";
export const INTERACTION_ADD_FAIL = "INTERACTION_ADD_FAIL";

export const INTERACTION_DELETE_REQUEST = "INTERACTION_DELETE_REQUEST";
export const INTERACTION_DELETE_SUCCESS = "INTERACTION_DELETE_SUCCESS";
export const INTERACTION_DELETE_FAIL = "INTERACTION_DELETE_FAIL";

export const INTERACTION_UPDATE_REQUEST = "INTERACTION_UPDATE_REQUEST";
export const INTERACTION_UPDATE_SUCCESS = "INTERACTION_UPDATE_SUCCESS";
export const INTERACTION_UPDATE_FAIL = "INTERACTION_UPDATE_FAIL";